version: "3.6"

services:
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    ports:
      - "9200:9200"
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - "transport.host=127.0.0.1"
      - "http.host=0.0.0.0"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"

  elasticsearch-ui:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.6.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  influxdb:
    image: influxdb:2.6
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=temperature
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin

  mongodb:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  mongodb-ui:
    image: mongo-express:latest
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=username
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password

  neo4j:
    image: neo4j:5.3.0
    ports:
      - '7474:7474' # https
      - '7473:7473' # http
      - '7687:7687' # bolt
    environment:
      - NEO4J_AUTH=neo4j/password

  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
    command: >
      --requirepass password
