version: "3.6"

services:
  influxdb:
    image: influxdb:1.8.10
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=username
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=database
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin

  mongodb:
    image: mongo:6.0.3
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  neo4j:
    image: neo4j:5.3.0
    ports:
      - '7474:7474' # https
      - '7473:7473' # http
      - '7687:7687' # bolt
    environment:
      - NEO4J_AUTH=neo4j/password

  redis:
    image: redis:7.0.8
    ports:
      - "6379:6379"
    command: >
      --requirepass password
