influxdb:
  url: http://localhost:8086/
  username: username
  password: password
  database: database

mongodb:
  url: localhost:27017
  username: username
  password: password
  database: database

neo4j:
  url: bolt://localhost:7687/
  username: neo4j
  password: password
