cassandra:
  data-center: datacenter1
  node: localhost
  port: 9042
  keyspace: flights
  enabled: false

elastic:
  url: http://localhost:9200/
  username: elastic
  password: password
  enabled: false

influxdb:
  url: http://localhost:8086/
  token: admin
  bucket: temperature
  organisation: org
  enabled: true

mongodb:
  url: localhost:27017
  username: username
  password: password
  database: database
  enabled: false

neo4j:
  url: bolt://localhost:7687/
  username: neo4j
  password: password
  enabled: false

redis:
  url: http://localhost:6379
  username: default
  password: password
  enabled: false
